import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar/Navbar";
import { Hero } from "@/components/Hero/hero";
import { Card } from "@/components/Card/card";
import { SliderCourse } from "@/components/courseSlider/slidercourse";
import { Content } from "@/components/Content/Content";
import SponserCard from "@/components/SponserSection/SponserCard";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Navbar/>
        <Hero/>
        <Content/>
       <SponserCard/> */}
        {children}
      </body>
    </html>
  );
}
